In [2]:
from keras.datasets import mnist

C:\Users\ASHU\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from keras import models
from keras import layers

In [9]:
network=models.Sequential()

In [10]:
network.add(layers.Dense(512,activation="relu",input_shape=(28*28,)))
network.add(layers.Dense(10,activation="softmax"))

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
network.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [12]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255

In [13]:
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

In [14]:
from keras.utils import to_categorical

In [15]:
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)

In [16]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [17]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 12s 193us/step - loss: 0.2564 - acc: 0.9262
Epoch 2/5
60000/60000 [==============================] - 11s 189us/step - loss: 0.1036 - acc: 0.96990s - loss: 0.1039 - ac
Epoch 3/5
60000/60000 [==============================] - 11s 190us/step - loss: 0.0684 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 12s 199us/step - loss: 0.0496 - acc: 0.9853
Epoch 5/5
60000/60000 [==============================] - 11s 179us/step - loss: 0.0370 - acc: 0.98911s - loss: 0.03


In [18]:
test_loss,test_acc=network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 104us/step


In [19]:
test_acc

0.9778